### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by VladimirKuznetsov** [Algoryx/AGXUnity-deprecated#18]
Hello,
Is this asset supposed to work with Dynamics For Space Claim? I've tried to run it with both x64 v1.5.1 and v1.3.0, but after I've built AgXUnity.dll, set up the scene and tried to run it, I got a Runtime Error "The application has requested the Runtime to terminate it in an unusual way".
https://s22.postimg.org/4hxgt222p/image.png

**Comment by vrguru** [comment]
No. You will need a full installation (and license) of AGX Dynamics.
Dynamics for SpaceClaim is a different product. 
Feel free to contact us at contact@algoryx.se
